acceptteleport: 20
teleporttime: 5
autosave: 300
automessagetime: 60
alerttime: 10
defaultgroup: "Gracz"
defaultnickcolor: "&6"
defaultmessagecolor: "&7"
automessage:
  - "&1&lTEST 5G MOC 500%"
  - "&2&lTEST 5G MOC 500%"
  - "&3&lTEST 5G MOC 500%"
  - "&4&lTEST 5G MOC 500%"
  - "&5&lTEST 5G MOC 500%"
  - "&6&lTEST 5G MOC 500%"
  - "&7&lTEST 5G MOC 500%"
  - "&8&lTEST 5G MOC 500%"
  - "&9&lTEST 5G MOC 500%"
  - "&a&lTEST 5G MOC 500%"
  - "&d&lTEST 5G MOC 500%"
  - "&f&lTEST 5G MOC 500%"
  - "&c&lTEST 5G MOC 500%"
spawn:
  world: world
  x: '0'
  y: '67'
  z: '0'
groups:
  Wlasciciel:
    date: '2020-06-30 10:19:52'
    author: Crystal_PL
    prefix: "&8&l[&4&lWlasciciel&8&l]"
    priority: 13
    format: "{PREFIX} &4&l{NICK} &8» {MESSAGE}"
    permissions:
      - "CrC.tools.permission"
    members: []
  Gracz:
    date: '2020-06-30 10:19:52'
    author: Crystal_PL
    prefix: "&8[&7Gracz&8]"
    priority: 1
    format: "{PREFIX} &b{NICK} &8» {MESSAGE}"
    permissions:
      - "CrC.tools.chat"
    members: []