acceptteleport: 20
teleporttime: 5
autosave: 300
automessagetime: 60
automessage:
  - "&1&lJebać krystala"
  - "&2&lJebać krystala"
  - "&3&lJebać krystala"
  - "&4&lJebać krystala"
  - "&5&lJebać krystala"
  - "&6&lJebać krystala"
  - "&7&lJebać krystala"
  - "&8&lJebać krystala"
  - "&9&lJebać krystala"
  - "&a&lJebać krystala"
  - "&d&lJebać krystala"
  - "&f&lJebać krystala"
  - "&c&lJebać krystala"
permission:
  feed:
    feed: "CrC.tools.feed"
    player: "CrC.tools.feed.player"
  heal:
    heal: "CrC.tools.heal"
    player: "CrC.tools.heal.player"
  tppos:
    tppos: "CrC.tools.tppos"
    player: "CrC.tools.tppos.player"
  exp:
    exp: "CrC.tools.exp"
    player: "CrC.tools.exp.player"
  fly:
    fly: "CrC.tools.fly"
    player: "CrC.tools.fly.player"
  speed:
    speed: "CrC.tools.speed"
    player: "CrC.tools.speed.player"
  tools:
    tools: "CrC.tools.tools"
  socialspy:
    socialspy: "CrC.tools.socialspy"
  gamemode:
    gamemode: "CrC.tools.gamemode"
    player: "CrC.tools.gamemode.player"
  repair:
    repair: "CrC.tools.repair"
  tp:
    tp: "CrC.tools.tp"
    player: "CrC.tools.tp.player"
  s:
    s: "CrC.tools.s"
  give:
    give: "CrC.tools.give"
  item:
    item: "CrC.tools.item"
  ip:
    player: "CrC.tools.ip"
  kick:
    all: "CrC.tools.kick.all"
    player: "CrC.tools.kick.player"
    bypass: "CrC.tools.kick.bypass"
  god:
    god: "CrC.tools.god"
  whois:
    whois: "CrC.tools.whois"