config:
  permission:
    feed:
      feed: "CrC.tools.feed"
      player: "CrC.tools.feed.player"
    heal:
      heal: "CrC.tools.heal"
      player: "CrC.tools.heal.player"
    tppos:
      tppos: "CrC.tools.tppos"
      player: "CrC.tools.tppos.player"
    exp:
      exp: "CrC.tools.exp"
      player: "CrC.tools.exp.player"