acceptteleport: 20
teleporttime: 5
autosave: 300
permission:
  feed:
    feed: "CrC.tools.feed"
    player: "CrC.tools.feed.player"
  heal:
    heal: "CrC.tools.heal"
    player: "CrC.tools.heal.player"
  tppos:
    tppos: "CrC.tools.tppos"
    player: "CrC.tools.tppos.player"
  exp:
    exp: "CrC.tools.exp"
    player: "CrC.tools.exp.player"
  fly:
    fly: "CrC.tools.fly"
    player: "CrC.tools.fly.player"
  speed:
    speed: "CrC.tools.speed"
    player: "CrC.tools.speed.player"
  tools:
    tools: "CrC.tools.tools"
  socialspy:
    socialspy: "CrC.tools.socialspy"
  gamemode:
    gamemode: "CrC.tools.gamemode"
    player: "CrC.tools.gamemode.player"
  repair:
    repair: "CrC.tools.repair"
  tp:
    tp: "CrC.tools.tp"
    player: "CrC.tools.tp.player"
  s:
    s: "CrC.tools.s"