acceptteleport: 20
teleporttime: 5
autosave: 300
automessagetime: 60
defaultgroup: "DZBAN"
automessage:
  - "&1&lTEST 5G MOC 500%"
  - "&2&lTEST 5G MOC 500%"
  - "&3&lTEST 5G MOC 500%"
  - "&4&lTEST 5G MOC 500%"
  - "&5&lTEST 5G MOC 500%"
  - "&6&lTEST 5G MOC 500%"
  - "&7&lTEST 5G MOC 500%"
  - "&8&lTEST 5G MOC 500%"
  - "&9&lTEST 5G MOC 500%"
  - "&a&lTEST 5G MOC 500%"
  - "&d&lTEST 5G MOC 500%"
  - "&f&lTEST 5G MOC 500%"
  - "&c&lTEST 5G MOC 500%"

permission:
  feed:
    feed: "CrC.tools.feed"
    player: "CrC.tools.feed.player"
  heal:
    heal: "CrC.tools.heal"
    player: "CrC.tools.heal.player"
  tppos:
    tppos: "CrC.tools.tppos"
    player: "CrC.tools.tppos.player"
  exp:
    exp: "CrC.tools.exp"
    player: "CrC.tools.exp.player"
  fly:
    fly: "CrC.tools.fly"
    player: "CrC.tools.fly.player"
  speed:
    speed: "CrC.tools.speed"
    player: "CrC.tools.speed.player"
  tools:
    tools: "CrC.tools.tools"
  socialspy:
    socialspy: "CrC.tools.socialspy"
  gamemode:
    gamemode: "CrC.tools.gamemode"
    player: "CrC.tools.gamemode.player"
  repair:
    repair: "CrC.tools.repair"
  tp:
    tp: "CrC.tools.tp"
    player: "CrC.tools.tp.player"
  s:
    s: "CrC.tools.s"
  give:
    give: "CrC.tools.give"
  item:
    item: "CrC.tools.item"
  ip:
    player: "CrC.tools.ip"
  kick:
    all: "CrC.tools.kick.all"
    player: "CrC.tools.kick.player"
    bypass: "CrC.tools.kick.bypass"
  god:
    god: "CrC.tools.god"
    player: "CrC.tools.god.player"
  whois:
    whois: "CrC.tools.whois"
  kill:
    kill: "CrC.tools.kill"
  warp:
    setwarp: "CrC.tools.warp.set"
    delwarp: "CrC.tools.warp.del"
    info: "CrC.tools.warp.info"
  sethome:
    player: "CrC.tools.sethome.player"
  delhome:
    player: "CrC.tools.delhome.player"
  home:
    player: "CrC.tools.home.player"
  setspawn:
    setspawn: "CrC.tools.setspawn"
  spawn:
    player: "CrC.tools.spawn.player"
  entity:
    clear: "CrC.tools.entity.clear"
  reload:
    reload: "CrC.tools.reload"
  chat:
    chat: "CrC.tools.chat"
    bypass: "CrC.tools.chat.bypass"
  permissions:
    permission: "CrC.tools.permission"

groups:
  DZBAN:
    date: '2020-06-30 10:19:52'
    author: Crystal_PL
    prefix: DZBAN
    priority: 2
    permissions: {}
    members: []
  DZBANEK:
    date: '2020-06-30 10:19:52'
    author: Crystal_PL
    prefix: DZBANEK123
    priority: 1
    permissions: {}
    members: []