name: CrCTools
version: 1.0
main: pl.crystalek.crctools.CrCTools
authors: [Crystal]
website: crystalek.pl
commands:
  feed:
  heal:
  tppos:
  exp:
  fly:
  speed:
  tpa:
  tpaccept:
  tools:
  tpdeny:
  msg:
  r:
  trybmsg:
  socialspy: