name: CrCTools
version: 1.0
main: pl.crystalek.crctools.CrCTools
authors: [Crystal]
website: crystalek.pl
depend: [ID-Library]
commands:
  feed:
  heal:
  tppos:
  exp:
  fly:
  speed:
  tpa:
  tpaccept:
    aliases: tak
  tools:
  tpdeny:
    aliases: nie
  tptoggle:
  msg:
    aliases:
      - w
      - tell
  r:
  trybmsg:
  socialspy:
  gamemode:
    aliases: gm
  repair:
    aliases: fix
  tp:
  s:
  give:
  i:
    aliases: item
  ip:
  kickall:
  god:
  whois:
  suicide:
  kill:
  setwarp:
  delwarp:
  warp:
  warpinfo:
  home:
  delhome:
  sethome:
  setspawn:
  spawn:
  entity:
  rlc:
  chat:
  perms:
    aliases: [cp, cperms, crystalperms]
  alert:
  tpall:
  mail:
  lore:
  rename:
  nick:
  tpahere:
  handgive: